### ISSUE TITLE
Remove warnings introduced in #32 when luigi == 3.1 is released

### ISSUE THREAD

**Issue by adrien-berchet** [BlueBrain/luigi-tools#34]
#32  was also merged in the main branch of luigi (https://github.com/spotify/luigi/pull/3170), so we will be able to remove it from luigi-tools as soon as a new release of luigi is available.

**Comment by arnaudon** [comment]
nice, it was fasst1

**Comment by adrien-berchet** [comment]
Yeah this time they were surprisingly reactive :stuck_out_tongue_winking_eye:
